// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: cicicache.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CiciCache_Get_FullMethodName = "/protobufs.ciciCache/Get"
)

// CiciCacheClient is the client API for CiciCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CiciCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type ciciCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewCiciCacheClient(cc grpc.ClientConnInterface) CiciCacheClient {
	return &ciciCacheClient{cc}
}

func (c *ciciCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, CiciCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CiciCacheServer is the server API for CiciCache service.
// All implementations must embed UnimplementedCiciCacheServer
// for forward compatibility.
type CiciCacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedCiciCacheServer()
}

// UnimplementedCiciCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCiciCacheServer struct{}

func (UnimplementedCiciCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCiciCacheServer) mustEmbedUnimplementedCiciCacheServer() {}
func (UnimplementedCiciCacheServer) testEmbeddedByValue()                   {}

// UnsafeCiciCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CiciCacheServer will
// result in compilation errors.
type UnsafeCiciCacheServer interface {
	mustEmbedUnimplementedCiciCacheServer()
}

func RegisterCiciCacheServer(s grpc.ServiceRegistrar, srv CiciCacheServer) {
	// If the following call pancis, it indicates UnimplementedCiciCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CiciCache_ServiceDesc, srv)
}

func _CiciCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CiciCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CiciCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CiciCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CiciCache_ServiceDesc is the grpc.ServiceDesc for CiciCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CiciCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobufs.ciciCache",
	HandlerType: (*CiciCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CiciCache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cicicache.proto",
}
